name: Release Plugins
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  proto-gen-grpc-plugin:
    strategy:
      matrix:
        lang: [ python ]
        os: [ ubuntu, macos ]
    env:
      LANG: ${{ matrix.lang }}
      OS: ${{ matrix.os }}
    name: protoc-gen-grpc-${{matrix.lang}}-${{matrix.os}}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: grpc/grpc
      - name: Cache Bazel
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Cache Bazel
        uses: actions/cache@v3
        if: runner.os == 'macOS'
        with:
          path: |
            /private/var/tmp/_bazel_runner/
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Build
        run: |
          echo "Building..."
          bazel build src/compiler:grpc_${{ env.LANG }}_plugin --enable_platform_specific_config
      - name: Package
        run: |
          cp bazel-bin/src/compiler/grpc_${{ env.LANG }}_plugin protoc-gen-grpc-${{ env.LANG }}
          tar czf protoc-gen-grpc-${{ env.LANG }}-${{ env.OS }}.tar.gz protoc-gen-grpc-${{ env.LANG }}
      - uses: actions/upload-artifact@v4
        with:
          name: protoc-gen-grpc-${{ env.LANG }}-${{ env.OS }}.tar.gz
          path: protoc-gen-grpc-${{ env.LANG }}-${{ env.OS }}.tar.gz
