name: Release Plugins
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  proto-gen-release:
    strategy:
      matrix:
        lang: [ python ]
        os: [ ubuntu, macos ]
    env:
      LANG: ${{ matrix.lang }}
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: grpc/grpc
      - name: Build
        run: |
          echo "Building..."
          bazel build src/compiler:grpc_${{ env.LANG }}_plugin --enable_platform_specific_config
      - name: Package
        run: |
          cd bazel-bin/src/compiler/
          cp grpc_${{ env.LANG }}_plugin grpc-${{ env.LANG }}-plugin
          tar czf grpc-${{ env.LANG }}-plugin-${{ env.OS }}.tar.gz grpc-${{ env.LANG }}-plugin
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bazel-bin/src/compiler/grpc-${{ env.LANG }}-plugin-${{ env.OS }}.tar.gz
          body: |
            grpc_${{ env.LANG }}_plugin v${{ env.VERSION }}
