name: Release Plugins
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  artifacts:
    strategy:
      matrix:
        lang: [ python ]
        version: [ 1.54.1 ]
        os: [ ubuntu-latest, macos-latest ]
    env:
      VERSION: ${{ matrix.version }}
      LANG: ${{ matrix.lang }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: grpc/grpc
          fetch-tags: true
          ref: refs/tags/v${{ env.VERSION }}
      - name: Build
        run: |
          echo "Building..."
          bazel build src/compiler:grpc_python_plugin
      - name: Asrchive artifacts
        run: |
          cd bazel-bin/src/compiler/
          cp grpc_${{ env.LANG }}_plugin grpc-${{ env.LANG }}-plugin
          tar czf grpc-${{ env.LANG }}-plugin.${{ env.VERSION }}.linux.amd64.tar.gz grpc-${{ env.LANG }}-plugin
      - name: Upload release grpc_${{ env.LANG }}_plugin
        uses: softprops/action-gh-release@v2
        with:
          files: bazel-bin/src/compiler/grpc-${{ env.LANG }}-plugin.${{ env.VERSION }}.linux.amd64.tar.gz
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: |
            grpc_${{ env.LANG }}_plugin v${{ env.VERSION }}
          draft: false
          prerelease: false
